// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Version {
    #[prost(uint32, tag = "1")]
    pub major: u32,
    #[prost(uint32, tag = "2")]
    pub minor: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SessionFrame {
    /// ! Which session this frame belongs to.
    #[prost(int64, tag = "1")]
    pub session_id: i64,
    /// ! ID of frame.
    #[prost(int64, tag = "2")]
    pub frame_id: i64,
    /// ! How long we thought the frame would take.
    #[prost(uint64, tag = "3")]
    pub predicted_frame_time_ns: u64,
    /// ! When we predicted the app should wake up.
    #[prost(uint64, tag = "4")]
    pub predicted_wake_up_time_ns: u64,
    /// ! When the client's GPU work should have completed.
    #[prost(uint64, tag = "5")]
    pub predicted_gpu_done_time_ns: u64,
    /// ! When we predicted this frame to be shown.
    #[prost(uint64, tag = "6")]
    pub predicted_display_time_ns: u64,
    /// ! The selected display period.
    #[prost(uint64, tag = "7")]
    pub predicted_display_period_ns: u64,
    /// !
    /// When the app told us to display this frame, can be different
    /// then the predicted display time so we track that separately.
    #[prost(uint64, tag = "8")]
    pub display_time_ns: u64,
    /// ! When the predict call was made (inside of xrWaitFrame).
    #[prost(uint64, tag = "9")]
    pub when_predicted_ns: u64,
    /// ! When the waiting thread was woken up.
    #[prost(uint64, tag = "10")]
    pub when_wait_woke_ns: u64,
    /// ! When xrBeginFrame was called.
    #[prost(uint64, tag = "11")]
    pub when_begin_ns: u64,
    /// ! When the layer information was delivered, (inside of xrEndFrame).
    #[prost(uint64, tag = "12")]
    pub when_delivered_ns: u64,
    /// ! When the scheduled GPU work was completed.
    #[prost(uint64, tag = "13")]
    pub when_gpu_done_ns: u64,
    /// ! Was this frame discarded.
    #[prost(bool, tag = "14")]
    pub discarded: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Used {
    /// ! Owning session of the frame.
    #[prost(int64, tag = "1")]
    pub session_id: i64,
    /// ! Which session frame was used by the compositor.
    #[prost(int64, tag = "2")]
    pub session_frame_id: i64,
    /// ! The system frame that the session was used by.
    #[prost(int64, tag = "3")]
    pub system_frame_id: i64,
    /// ! When the frame was latched.
    #[prost(uint64, tag = "4")]
    pub when_ns: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SystemFrame {
    /// ! ID of frame.
    #[prost(int64, tag = "1")]
    pub frame_id: i64,
    /// ! Projected pixels to photon time.
    #[prost(uint64, tag = "2")]
    pub predicted_display_time_ns: u64,
    /// ! Current period of displaying of frames.
    #[prost(uint64, tag = "3")]
    pub predicted_display_period_ns: u64,
    /// ! When the compositor should hand pixels to display hardware.
    #[prost(uint64, tag = "4")]
    pub desired_present_time_ns: u64,
    /// ! The time that the compositor should wake up.
    #[prost(uint64, tag = "5")]
    pub wake_up_time_ns: u64,
    #[prost(uint64, tag = "6")]
    pub present_slop_ns: u64,
}
/// !
/// Out of band info about a GPU timing from a system compositor.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SystemGpuInfo {
    /// ! ID of frame.
    #[prost(int64, tag = "1")]
    pub frame_id: i64,
    /// ! Start of GPU work.
    #[prost(uint64, tag = "2")]
    pub gpu_start_ns: u64,
    /// ! End of GPU work.
    #[prost(uint64, tag = "3")]
    pub gpu_end_ns: u64,
    /// ! When the information was gathered.
    #[prost(uint64, tag = "4")]
    pub when_ns: u64,
}
/// !
/// Information that comes from the vulkan present timing.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SystemPresentInfo {
    /// ! ID of frame.
    #[prost(int64, tag = "1")]
    pub frame_id: i64,
    /// ! The total expected time for the compositor to complete a frame.
    #[prost(uint64, tag = "2")]
    pub expected_comp_time_ns: u64,
    /// ! The time we predicted the compositor to wake up time.
    #[prost(uint64, tag = "3")]
    pub predicted_wake_up_time_ns: u64,
    /// ! Predicted time for completion of the GPU work.
    #[prost(uint64, tag = "4")]
    pub predicted_done_time_ns: u64,
    /// ! Predicted display time.
    #[prost(uint64, tag = "5")]
    pub predicted_display_time_ns: u64,
    /// ! When was this frame predicted.
    #[prost(uint64, tag = "6")]
    pub when_predict_ns: u64,
    /// ! When we last woke up the compositor after its equivalent of wait_frame.
    #[prost(uint64, tag = "7")]
    pub when_woke_ns: u64,
    /// ! When the compositor started rendering a frame
    #[prost(uint64, tag = "8")]
    pub when_began_ns: u64,
    /// ! When the compositor finished rendering a frame
    #[prost(uint64, tag = "9")]
    pub when_submitted_ns: u64,
    /// ! When new frame timing info was last added.
    #[prost(uint64, tag = "10")]
    pub when_infoed_ns: u64,
    /// ! When we wanted to start presenting.
    #[prost(uint64, tag = "11")]
    pub desired_present_time_ns: u64,
    /// ! The slop used for this frame.
    #[prost(uint64, tag = "12")]
    pub present_slop_ns: u64,
    /// ! Margin of GPU to present time.
    #[prost(uint64, tag = "13")]
    pub present_margin_ns: u64,
    /// ! When the present time actually happened.
    #[prost(uint64, tag = "14")]
    pub actual_present_time_ns: u64,
    /// ! The earliest we could have presented.
    #[prost(uint64, tag = "15")]
    pub earliest_present_time_ns: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Record {
    #[prost(oneof = "record::Record", tags = "1, 2, 3, 4, 5, 6")]
    pub record: ::core::option::Option<record::Record>,
}
/// Nested message and enum types in `Record`.
pub mod record {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Record {
        #[prost(message, tag = "1")]
        Version(super::Version),
        #[prost(message, tag = "2")]
        SessionFrame(super::SessionFrame),
        #[prost(message, tag = "3")]
        Used(super::Used),
        #[prost(message, tag = "4")]
        SystemFrame(super::SystemFrame),
        #[prost(message, tag = "5")]
        SystemGpuInfo(super::SystemGpuInfo),
        #[prost(message, tag = "6")]
        SystemPresentInfo(super::SystemPresentInfo),
    }
}
