[package]
name = "dash-frontend"
version = "0.1.0"
edition = "2024"
description = "The dashboard frontend for WayVR"
license = "GPL-3.0-only"
authors = ["galister", "oo8dev"]
repository = "https://github.com/wlx-team/wayvr"

[dependencies]
wayvr-ipc = { path = "../wayvr-ipc", default-features = false }
wgui = { path = "../wgui/" }
wlx-common = { path = "../wlx-common" }

anyhow.workspace = true
chrono.workspace = true
glam = { workspace = true, features = ["mint", "serde"] }
log.workspace = true
rust-embed.workspace = true
serde = { workspace = true, features = ["rc"] }
serde_json.workspace = true
smol = { workspace = true }
strum.workspace = true
uuid.workspace = true
xdg.workspace = true

keyvalues-parser = "0.2.4"
lz4_flex = { version = "0.13.1", features = ["frame"] }
ureq = "3.3.0"
rand = "0.10.2"

[features]
default = ["monado"]
monado = []
