name: Build AppImage

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'staging'
      - 'test-*'

env:
  APPDIR: WayVR.AppDir
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build_appimage:
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: aarch64
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        working-directory: ./wayvr
    steps:
      - uses: actions/checkout@v3
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Prepare Environment
        run: |
          ../.github/workflows/scripts/appimage_prepare_env.sh
      - name: Cargo Build
        run: |
          ../.github/workflows/scripts/appimage_build_wlx.sh
      - name: Build xwayland-satellite
        run: |
          ../.github/workflows/scripts/appimage_build_satellite.sh
      - name: Package AppImage
        run: |
          ../.github/workflows/scripts/appimage_package.sh
      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: WayVR-${{ github.ref_name }}-${{ matrix.arch }}.AppImage
          path: ./wayvr/WayVR-${{ matrix.arch }}.AppImage
      - name: Upload AppImage zsync
        uses: actions/upload-artifact@v4
        with:
          name: WayVR-${{ github.ref_name }}-${{ matrix.arch }}.AppImage.zsync
          path: ./wayvr/WayVR-${{ matrix.arch }}.AppImage.zsync
